import type { CSSProperties } from "react";

export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  alert: (fg: string, bg: string): CSSProperties => ({
    border: `1px solid ${fg}`,
    background: bg,
    borderRadius: 8,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  }),
  alertHead: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  alertTitle: { fontSize: 12.5, letterSpacing: "0.02em", flex: 1 } satisfies CSSProperties,
  alertHint: { fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  signalList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  signal: { display: "flex", alignItems: "baseline", gap: 8, fontSize: 12 } satisfies CSSProperties,
  signalLine: {
    minWidth: 26,
    textAlign: "right",
    color: "var(--text-muted)",
    fontVariantNumeric: "tabular-nums",
  } satisfies CSSProperties,
  signalRule: { color: "var(--text-primary)", fontWeight: 600, whiteSpace: "nowrap" } satisfies CSSProperties,
  signalExcerpt: {
    color: "var(--text-secondary)",
    fontSize: 11.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } satisfies CSSProperties,
  row: { display: "flex", alignItems: "baseline", gap: 10 } satisfies CSSProperties,
  label: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  value: { fontSize: 13, color: "var(--text-primary)" } satisfies CSSProperties,
  body: {
    marginTop: 6,
    maxHeight: 200,
    overflow: "auto",
    background: "var(--code-bg)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: 10,
    fontSize: 12,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)", marginTop: 4 } satisfies CSSProperties,
  ignoredList: {
    margin: "6px 0 0",
    paddingLeft: 18,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  notice: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
} as const;
