import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 12,
    color: "var(--text-primary)",
    outline: "none",
    width: 180,
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5, marginBottom: 20 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "20px 0 8px",
  } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  overlayRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--accent)",
    background: "var(--bg-elevated)",
    boxShadow: "0 12px 32px rgba(0,0,0,.55)",
    cursor: "grabbing",
    transform: "scale(1.02)",
  } satisfies CSSProperties,
  listOver: {
    outline: "1px dashed var(--accent)",
    outlineOffset: 4,
    borderRadius: 8,
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    marginBottom: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  attachedRow: (dragging: boolean, dimmed: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    marginBottom: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    opacity: dragging ? 0 : dimmed ? 0.55 : 1,
  }),
  handle: (dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    color: dragging ? "var(--text-primary)" : "var(--text-muted)",
    cursor: dragging ? "grabbing" : "grab",
    touchAction: "none",
  }),
  position: {
    width: 20,
    flexShrink: 0,
    fontSize: 12,
    color: "var(--text-muted)",
    textAlign: "right",
  } satisfies CSSProperties,
  name: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    fontWeight: 500,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  disabledNote: { fontSize: 11, color: "var(--warn)" } satisfies CSSProperties,
  blockedRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    marginBottom: 6,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  blockedNote: { fontSize: 11, color: "var(--crit)", whiteSpace: "nowrap" } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "8px 2px" } satisfies CSSProperties,
} as const;
