import type { CSSProperties } from "react";

export const s = {
  banner: (fg: string, bg: string): CSSProperties => ({
    borderBottom: `1px solid ${fg}`,
    background: bg,
    padding: "12px 28px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    flexShrink: 0,
  }),
  head: { display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  title: (fg: string): CSSProperties => ({
    fontSize: 12.5,
    fontWeight: 700,
    letterSpacing: "0.03em",
    color: fg,
    whiteSpace: "nowrap",
  }),
  body: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    flex: 1,
    minWidth: 240,
  } satisfies CSSProperties,
  signalList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  signal: { display: "flex", alignItems: "baseline", gap: 8, fontSize: 12 } satisfies CSSProperties,
  signalLine: {
    minWidth: 26,
    textAlign: "right",
    color: "var(--text-muted)",
    fontVariantNumeric: "tabular-nums",
  } satisfies CSSProperties,
  signalRule: { fontWeight: 600, whiteSpace: "nowrap" } satisfies CSSProperties,
  signalExcerpt: {
    color: "var(--text-secondary)",
    fontSize: 11.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } satisfies CSSProperties,
  acceptRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  acceptLabel: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 12.5,
    color: "var(--text-primary)",
    lineHeight: 1.45,
    flex: 1,
    minWidth: 260,
    cursor: "pointer",
  } satisfies CSSProperties,
  checkbox: { marginTop: 2, accentColor: "var(--crit)" } satisfies CSSProperties,
  acceptedOn: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
